SELECT SUM(SCORE) AS SCORE
        ,G.EMP_NO
        ,E.EMP_NAME
        ,E.POSITION
        ,E.EMAIL
FROM HR_EMPLOYEES E
INNER JOIN HR_GRADE G ON G.EMP_NO = E.EMP_NO
GROUP BY EMP_NO, YEAR
HAVING G.YEAR = '2022'
ORDER BY SCORE DESC
LIMIT 1